# Generated by Django 6.0.2 on 2026-02-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el correo electrónico ha sido verificado', verbose_name='Correo Verificado'),
        ),
    ]
