# Generated by Django 5.2.10 on 2026-03-13 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Razón Social / Nombre')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('currency', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar Estadounidense')], default='MXN', max_length=3, verbose_name='Moneda Base')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este usuario (Tenant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
    ]
