# Generated by Django 6.0.2 on 2026-04-14 03:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='costing_method',
            field=models.CharField(choices=[('average', 'Costo Promedio'), ('fifo', 'PEPS (Primeras Entradas, Primeras Salidas)'), ('lifo', 'UEPS (Últimas Entradas, Primeras Salidas)')], default='average', max_length=10, verbose_name='Método de Costeo'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('finished', 'Producto Terminado'), ('raw', 'Materia Prima'), ('component', 'Componente')], default='finished', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('PZA', 'Pieza'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('CJ', 'Caja'), ('PQ', 'Paquete'), ('JG', 'Juego'), ('SR', 'Servicio')], default='PZA', max_length=5, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='running_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Saldo Acumulado'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_at_movement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Costo Unitario al Movimiento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes (ej. XAXX010101000)', max_length=13, validators=[django.core.validators.RegexValidator(message='RFC inválido. Formato: 3-4 letras + 6 dígitos + 3 caracteres alfanuméricos.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')], verbose_name='RFC'),
        ),
    ]
