# Generated by Django 5.2.10 on 2026-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clave_producto_sat',
            field=models.CharField(blank=True, help_text='Clave de 8 dígitos del catálogo del SAT (ej. 43211500)', max_length=8, null=True, verbose_name='Clave Producto/Servicio SAT'),
        ),
        migrations.AddField(
            model_name='product',
            name='clave_unidad_sat',
            field=models.CharField(blank=True, help_text='Clave de unidad del SAT (ej. H87 para piezas)', max_length=3, null=True, verbose_name='Clave Unidad SAT'),
        ),
    ]
