# Generated by Django 5.2.10 on 2026-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Clave Producto/Servicio')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Clave Producto SAT',
                'verbose_name_plural': 'Claves Productos SAT',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SatUnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Clave Unidad')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Unidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Clave Unidad SAT',
                'verbose_name_plural': 'Claves Unidades SAT',
                'ordering': ['code'],
            },
        ),
    ]
