# Generated by Django 5.2.10 on 2026-03-27 05:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_satproductcode_satunitcode'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
