# Generated by Django 5.2.10 on 2026-04-22 01:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_enable_postgres_extensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='satproductcode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='sat_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
