# Generated by Django 5.2.10 on 2026-04-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_product_brand_product_costing_method_and_more'),
        ('logistica', '0004_sat_product_pg_index'),
    ]

    operations = [
    ]
